# Numpy2

## 숙제검사

## 1. 행렬데이터의 선택

### 1.1. 요소지정
- 기본 파이썬 형식 배열 요소 지정 가능([x][y])
    - 왼쪽부터 차례대로 '가장 큰 차원' = 가장 큰 차원부터 선택
- 한 bracket내 ,로 한번에 요소 지정 가능
    - 순서는 [행, 열]
    - 왼쪽부터 차례대로 '가장 큰 차원'이라고 생각하면 간단

In [2]:
ls =  [[10, 20, 30], [60, 70, 80], [90, 91, 92]]
ls[1][2]

80

In [4]:
import numpy as np

In [7]:
ar = np.array([[10, 20, 30], [60, 70, 80], [90, 91, 92]])
print(ar)
print(ar[1]) # 가장 큰 차원(행)부터 선택
print(ar[1][2]) # 80
print(ar[1,2]) # 80 동일
print(ar[1,1]) # ar[1][1] 동일

[[10 20 30]
 [60 70 80]
 [90 91 92]]
[60 70 80]
80
80
70


### 1.2. 슬라이싱
- 요소지정의 범위버전, 사실상 python슬라이싱과 비슷하다
- `-`기호도 사용 가능

In [8]:
ar = np.arange(0,9).reshape((3,3))
print(ar)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### ar[:]

- ar의 모든 row (= ar)

#### ar[0]

- row 0

#### ar[1]

- row 1

#### ar[:,1]

- col 1

#### ar[1:]

- row 1 이후，ar[1:,] 혹은 ar[1:，:]와 동일한 표현

#### ar[:2]

- row 0~1

#### ar[:2,1:]

- row 0-1, col 1 이후

#### ar[:2,:2]

- row 0〜1, col 0-1

#### ar[2,:2]

- row 2, col 0~1

#### ar[:,2]

- col 2

#### ar[:.1:3]

- col 1~2

## * c vs f?
- c: `C`언어 타입, 혹은 contiguous(인접한)의 약어, 수학적으로 row(행) major
- f: `Fortran`언어 타입, 수학적으로 column(열) major

In [14]:
arr = np.arange(12).reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
arr2 = np.arange(12).reshape(4, 3, order='F')
arr2

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## 2. 행렬데이터의 연산

### 2.1. 기본 연산
- list의 연산 =/= ndarry의 연산

In [16]:
ls = [1, 2, 3]
ls * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [17]:
na = np.array([1, 2, 3])
na * 3

array([3, 6, 9])

### 2.2. 비교 연산

In [18]:
na2 = np.array([4, 5, 6])
na, na2

(array([1, 2, 3]), array([4, 5, 6]))

In [19]:
na == 2, na2 > 4

(array([False,  True, False]), array([False,  True,  True]))

## * 뷰
- call by reference와 비슷하게 주소를 이용하는 개념
- 행렬에 어떤 조작이 가해졌을 시 그 결과를 '뷰'로 리턴
- '뷰'에 조작을 가하면 원본도 변경된다
- 판다스와 다른점

In [11]:
ar = np.array([[10, 20, 30], [60, 70, 80], [90, 91, 92]])
v = ar[1]
v[:] = 50
ar

array([[10, 20, 30],
       [50, 50, 50],
       [90, 91, 92]])

### 2.3. 필터링(불리언인덱싱)
- 비교연산 결과에서 True값만 남음
- 배열함수의 filter와 동일한 기능

In [20]:
na[na == 2], na2[na2 > 4]

(array([2]), array([5, 6]))

- 예제1) 3의 배수만 출력

In [21]:
na3 = np.arange(10)
na3[na3 % 3 == 0]

array([0, 3, 6, 9])

- 예제1-1) 3의 배수만 0으로

In [2]:
na3 = np.arange(10)
na3[na3 % 3 == 0] = 0
na3

array([0, 1, 2, 0, 4, 5, 0, 7, 8, 0])

- 예제2) 두개의 ndarray에서 같은 데이터만 남기기

In [ ]:
na1 = np.array([1, 2, 3, 4, 5])
na2 = np.array([1, 0, 3, 0, 5])
na1[na1 == na2]

### 2.4. 브로드캐스팅
- 브로드 캐스팅은 행과 열이 동일하지 않은 ndarray의 연산에 대해 강제적으로 그 크기를 맞춰주어 element wise연산을 행하는 것

In [23]:
mx1 = np.array([[0]*3, [10]*3, [20]*3, [30]*3])
mx1

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [24]:
mx1 + 10

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40]])

In [25]:
mx2 = np.array([[0]*3, [10]*3, [20]*3, [30]*3])
mx2

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [26]:
mx1 + mx2

array([[ 0,  0,  0],
       [20, 20, 20],
       [40, 40, 40],
       [60, 60, 60]])

In [32]:
# row vector add
mx3 = np.arange(3)
mx3

array([0, 1, 2])

In [33]:
mx1 + mx3

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [38]:
# column vector add
mx4 = np.array([[1, 2, 3, 4]]).T # T is transpose
mx4

array([[1],
       [2],
       [3],
       [4]])

In [39]:
mx1 + mx4

array([[ 1,  1,  1],
       [12, 12, 12],
       [23, 23, 23],
       [34, 34, 34]])

In [40]:
# column vector plus row vector
mx4 + mx3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### 자, 그럼 행렬곱을 실행해볼까?

In [41]:
mx5 = np.array([[0]*3, [10]*3, [20]*3])
mx5

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20]])

In [42]:
mx1 * mx5

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [43]:
np.dot(mx1, mx5)

array([[  0,   0,   0],
       [300, 300, 300],
       [600, 600, 600],
       [900, 900, 900]])

In [44]:
np.matmul(mx1, mx5)

array([[  0,   0,   0],
       [300, 300, 300],
       [600, 600, 600],
       [900, 900, 900]])

### * dot vs matmul?
- 2D array에서 차이 없음
- matmul은 기본적으로 matrix간의 연산만 지원(최소 2차원 이상)
- dot은 matrix가 아니더라도 내적 수행

In [45]:
np.dot([1, 2, 3, 4, 5], 5)

array([ 5, 10, 15, 20, 25])

In [46]:
np.matmul([1, 2, 3, 4, 5], 5)

ValueError: Scalar operands are not allowed, use '*' instead

### 2.5. Fancy indexing

In [6]:
mx1 = np.array([[0,1,2], [10, 12, 13], [20]*3, [30]*3])
mx1

array([[ 0,  1,  2],
       [10, 12, 13],
       [20, 20, 20],
       [30, 30, 30]])

In [7]:
mx1[[0, 2, -1]]

array([[ 0,  1,  2],
       [20, 20, 20],
       [30, 30, 30]])

In [8]:
mx1[:, [0, 2, -1]]

array([[ 0,  2,  2],
       [10, 13, 13],
       [20, 20, 20],
       [30, 30, 30]])

## 3. 기초통계량(numpy 함수들)
- min : 최소값
- max : 최대값
- argmin : 최소값의 위치 index
- argmax : 최대값의 위치 index
- sum : 모든 행렬의 요소를 더해줌
- mean : 평균
- median : 중간값 (값이 짝수일경우에는 중간값 두개의 수의 평균)
- var : 분산
- std : 표준편차

## 4. all, any
- all: 행렬 데이터를 비교연산한 결과가 하나라도 false이면 false (and 유사) [전부 다 참이어야 true]
- any: 행렬 데이터를 비교연산한 결과가 하나라도 true이면 true (or 유사) [그 중 하나라도 참이면 true]

In [4]:
na = np.array([1, 2, 3])
na == 2, np.all(na == 2), np.any(na == 2)

(array([False,  True, False]), False, True)

## 5. compare performance - 퍼포먼스 비교
- 10**7 개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간

In [5]:
# 정의
ls = []
size = int(1E7)

- list comprehension으로 생성

In [7]:
%%time
ls = [num for num in range(size)]
print(len(ls))

10000000
Wall time: 1.05 s


- numpy arange로 생성

In [8]:
%%time
na = np.arange(size)
print(len(na))

10000000
Wall time: 23 ms


10**7 개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간
- for문을 이용하여 수행

In [9]:
%%time
count = 0
for idx in ls:
    if (ls[idx] % 3 == 0) or (ls[idx] % 5 == 0):
        count += 1
print(count)

4666667
Wall time: 2.41 s


10**7 개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간
- list comprehention을 이용하여 수행

In [10]:
%%time
result = [value for value in ls if (value % 3 == 0) or (value % 5 == 0)]
count = len(result)
print(count)

4666667
Wall time: 1.07 s


10**7 개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간
- numpy를 이용하여 수행

In [11]:
%%time
count = len(na[(na % 3 == 0) | (na % 5 == 0)])
print(count)

4666667
Wall time: 235 ms
