In [1]:
import numpy as np

ar[0][1] == ar[0,1]

ar = np.array([],[],[])

In [56]:
ar1 = np.arange(0, 9).reshape([3,3])
ar1[:]
ar1[0]
ar1[:,1]
ar1[1:]
ar1[:2,1:]
ar1[:2, :2]
ar1[2,:2]
ar1[:,2]
ar1[:,1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])

randint -> end 값 포함
나머지는 end - 1 까지 포함

c(행우선:row) vs f(열우선:colulmn)

In [11]:
ar2 = np.arange(0,12).reshape(4,3)
ar2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
ar3 = np.arange(0,12).reshape(4,3, order=f)
ar3

NameError: name 'f' is not defined

In [ ]:
list * 3
nparray * 3


view
broadcasting
filtering (boolean indexing)
ar = [1,2,3]
ar[ar==2] -> ar[[F,T,F]]

In [35]:
aa = np.arange(1, 10)
aa[aa%3==0] = 0
aa

array([1, 2, 0, 4, 5, 0, 7, 8, 0])

In [40]:
bb = np.array([1,2,4,8])
cc = np.array([0,2,4,0])
bb[bb==cc]

array([2, 4])

In [43]:
ar4 = np.array([[0]* 3, [10]*3])
ar4
ar4 + 10

array([[10, 10, 10],
       [20, 20, 20]])

In [ ]:
# row vector

In [44]:
# column vector

mx4 = np.array([[1,2,3,4]]).T
# T  transpose
mx4

array([[1],
       [2],
       [3],
       [4]])

In [47]:
# np.dot
# np.matmul -> @
# mx1.matmul(mx5) -> mx1@mx2

np.dot([1,2,3,4,5], 5)

array([ 5, 10, 15, 20, 25])

In [59]:
mx1 = np.array([1,2,3,4,5])
mx2 = np.array([6,7,8,9,10])

mx1.dot(mx2)
mx1.matmul(mx2)
mx1@mx2

AttributeError: 'numpy.ndarray' object has no attribute 'matmul'

In [ ]:
# fancy indexing
mx1[:, [0,2,-1]]

# and (&)
# or (|)