# numpy
# pandas

In [2]:
import numpy as np

In [5]:
ar = np.array((10, 20, 30))

ar = np.array([1, 2, 3])

ar = np.array(range(5))

print(ar, ar[0], ar[2])
print(type(ar))
print(ar.ndim)
print(ar.shape)
print(ar.size)

[0 1 2 3 4] 0 2
<class 'numpy.ndarray'>
1
(5,)
5


In [ ]:
# array : 리터럴 값, ndarray : 행열 기준

In [8]:
a = (1)
b = (1,)

print(type(a), type(b))

<class 'int'> <class 'tuple'>


In [11]:
ar1 = np.array([[10, 20, 30], [40, 50, 60]])

ar1, ar1.ndim, ar1.shape

(array([[10, 20, 30],
        [40, 50, 60]]), 2, (2, 3))

In [16]:
zero = np.zeros((2, 3))
zero, zero.astype(str)

(array([[0., 0., 0.],
        [0., 0., 0.]]), array([['0.0', '0.0', '0.0'],
        ['0.0', '0.0', '0.0']], dtype='<U32'))

In [18]:
one = np.ones((4, 3), dtype=int)
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
eye = np.eye(3)

identity = np.identity(3)

eye, identity


(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [22]:
np.random.random((2, 3))

array([[0.85124278, 0.46267681, 0.10707771],
       [0.94020772, 0.30179053, 0.96101573]])

In [24]:
np.random.rand(2, 3)

array([[0.19917775, 0.25331184, 0.04445732],
       [0.67361889, 0.95019333, 0.17940381]])

In [27]:
r = np.random.randint(1, 10, (3, 4))
r

array([[6, 1, 6, 6],
       [1, 3, 1, 1],
       [5, 2, 4, 2]])

In [30]:
np.random.shuffle(r)
r

array([[5, 2, 4, 2],
       [6, 1, 6, 6],
       [1, 3, 1, 1]])

In [32]:
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.3, 0.2])

array([2, 2, 3, 3, 3, 3, 0, 4, 0, 2])

In [35]:
ar2 = np.arange(10)
ar2

np.reshape(ar2, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
# r = np.random.randint(1, 10, (3, 4)) 로 생성된 r 을 모든 차원에 대하여 shuffle

r = np.random.randint(1, 10, (3, 4)) 
r

array([[4, 1, 1, 2],
       [1, 3, 7, 1],
       [2, 5, 9, 9]])

In [155]:
re = r.reshape(r.size)
re

array([5, 9, 7, 1, 3, 9, 2, 4, 1, 1, 1, 2])

In [172]:
np.random.shuffle(re)

r = np.reshape(re, (3, 4))
r
# np.reshape(r, r.shape)

array([[4, 5, 9, 1],
       [1, 7, 1, 3],
       [9, 2, 2, 1]])

In [179]:
r.flatten()
r.ravel()

r.dtype, r.astype('float')

(dtype('int64'), array([[4., 5., 9., 1.],
        [1., 7., 1., 3.],
        [9., 2., 2., 1.]]))

가로 결합 : 
행의 개수가 맞다.
열방향
행기준
axis = 1

세로 결합 :
열의 개수가 맞다.
행방향
열기준
axis = 0

In [ ]:
# sort(axis=)

r = np.random.randint(1, 10, (3, 4)) 로 생성된 r 을 모든 차원에 대하여 shuffle

In [3]:
r1 = np.random.randint(1, 10, (3, 4))
r1

array([[5, 2, 7, 3],
       [3, 6, 1, 7],
       [3, 5, 1, 6]])

In [4]:
r2 = r1.copy()
r2

array([[5, 2, 7, 3],
       [3, 6, 1, 7],
       [3, 5, 1, 6]])

In [5]:
r3 = r2.reshape(r2.size)
r3

array([5, 2, 7, 3, 3, 6, 1, 7, 3, 5, 1, 6])

In [6]:
np.random.shuffle(r3)
r3.reshape(r2.shape)

array([[6, 6, 3, 5],
       [7, 1, 7, 3],
       [2, 5, 1, 3]])